FROM python:3.8

EXPOSE 7878

# list of comma separated strings
ENV MODULES=""

ENV PT__auth__hash__algo="argon2"
ENV PT__log_level="INFO"

RUN mkdir ~/.papertext

RUN apt-get update
RUN apt-get install --no-install-recommends -y \
    build-essential \
    libmpc-dev
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

# install optional dependency of paperback
RUN pip install orjson --no-cache-dir

# install optional dependencies of auth module
RUN pip install argon2-cffi gmpy2 --no-cache-dir


RUN python3.8 -m pip install --upgrade pip
RUN python3.8 -m pip install --upgrade setuptools

WORKDIR /root

COPY README.md      ./paperback/
COPY LICENSE        ./paperback/
COPY pyproject.toml ./paperback/
COPY src/paperback  ./paperback/src/paperback

RUN python3.8 -m pip install -e ./paperback

COPY src/container/install_deps.sh ./install_deps.sh
RUN ./install_deps.sh

CMD paperback run
