version: "3.7"
services:
  paperback:
    image: quay.io/papertext/paperback:latest
    networks:
      - backend
      - frontend
    ports:
      - "7878:7878"
    logging:
      driver: json-file
    depends_on:
      - relational_db
      - graph_db
    links:
      - "relational_db"
      - "graph_db"
    environment:
      SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
      PT__log_level: "DEBUG"
      PT__core__host: "0.0.0.0"
      PT__auth__IPstack_api_key: $IPstack_api_key
      PT__auth__db__host: "relational_db"
      PT__auth__db__user: "paperback"
      PT__auth__db__dbname: "auth_module"
      PT__auth__db__password: $psql_password
      PT__auth__token__generate_keys: $PT__auth__token__generate_keys
      PT__docs__processor__host: $PT__docs__processor__host
      PT__docs__processor__service: $PT__docs__processor__service
      PT__docs__graph_db__host: "graph_db"
      PT__docs__graph_db__auth__password: $neo4j_password
#    deploy:
#      mode: global
#      resources:
#        limits:
#          cpus: '0.25'
#          memory: 10Gb
#        reservations:
#          cpus: '0.10'
#          memory: 50Gb
#      restart_policy:
#        condition: on-failure
#        max_attempts: 3
#        window: 120s

  relational_db:
    image: postgres:13
    networks:
      - backend
    logging:
      driver: json-file
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.25'
          memory: 10Gb
        reservations:
          cpus: '0.10'
          memory: 50Gb
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    environment:
      POSTGRES_PASSWORD: $psql_password
      paperback_dbuser_passwd: $psql_password
    ports:
      - "5432:5432"
    volumes:
      - "~/.papertext/postgresql:/var/lib/postgresql/data:z"
      - ".init_graph_db.sh:/container-entrypoint-initdb.d/init-user-db.sh:z"

  graph_db:
    image: neo4j:4.1.1
    networks:
      - backend
    logging:
      driver: json-file
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "~/.papertext/neo4j:/data:z"
    environment:
       NEO4J_AUTH: "neo4j/$neo4j_password"
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.25'
          memory: 10Gb
        reservations:
          cpus: '0.10'
          memory: 50Gb
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s

networks:
  backend:
  frontend:
