variables:
  GIT_DEPTH: 10
  GIT_SUBMODULE_STRATEGY: none
  GROUP_NAME: papertext
  PROJECT_NAME: paperback

stages:
  - build
  - deploy

conteinerize:
  stage: build
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: rootless
  ##
  ## use buildah instead of dind to build containers
  ##
  image:
    name: registry.gitlab.com/unrndm/buildah-in-container:latest
  before_script:
    - echo $CONTAINER_REGISTRY_PASS | buildah login -u $CONTAINER_REGISTRY_USER --password-stdin $CONTAINER_REGISTRY_LINK
  script:
    # builda doesn't currently support cache-from, uncomment and remove next command when added
    # - buildah pull $CONTAINER_REGISTRY_LINK/$GROUP_NAME/$PROJECT_NAME:latest || true
    # - buildah bud \
    #   --cache-from $CONTAINER_REGISTRY_LINK/$GROUP_NAME/$PROJECT_NAME:latest \
    #   --tag $CONTAINER_REGISTRY_LINK/$GROUP_NAME/$PROJECT_NAME:latest \
    #   --tag $CONTAINER_REGISTRY_LINK/$GROUP_NAME/$PROJECT_NAME:$CI_COMMIT_SHA \
    #   .
    - buildah bud \
        . \
        --tag $CONTAINER_REGISTRY_LINK/$GROUP_NAME/$PROJECT_NAME:latest \
        --tag $CONTAINER_REGISTRY_LINK/$GROUP_NAME/$PROJECT_NAME:$CI_COMMIT_SHA
    - buildah push $CONTAINER_REGISTRY_LINK/$GROUP_NAME/$PROJECT_NAME:latest
    - buildah push $CONTAINER_REGISTRY_LINK/$GROUP_NAME/$PROJECT_NAME:$CI_COMMIT_SHA

deploy prod:
  stage: deploy
  only:
    refs:
      - prod
  trigger:
    project: papertext/dev
    branch: prod

deploy dev:
  stage: deploy
  only:
    refs:
      - dev
  trigger:
    project: papertext/dev
    branch: dev
