variables:
  GIT_DEPTH: 10
  GIT_SUBMODULE_STRATEGY: none
  GROUP_NAME: papertext
  PROJECT_NAME: paperback

stages:
  - build
  - deploy

conteinerize:
  stage: build
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: rootless
  ##
  ## use buildah instead of dind to build containers
  ##
  image:
    name: registry.gitlab.com/unrndm/buildah-in-container:latest
  before_script:
    - echo $CONTAINER_REGISTRY_PASS | buildah login -u $CONTAINER_REGISTRY_USER --password-stdin $CONTAINER_REGISTRY_LINK
  script:
    # builda doesn't currently support cache-from, uncomment and remove next command when added
    # - buildah pull registry.gitlab.com/papertext/paperback:latest || true
    # - buildah bud \
    #   --cache-from registry.gitlab.com/papertext/paperback:latest \
    #   --tag registry.gitlab.com/papertext/paperback:latest \
    #   --tag registry.gitlab.com/papertext/paperback:$CI_COMMIT_SHA \
    #   .
    - buildah bud --tag registry.gitlab.com/papertext/paperback:latest --tag registry.gitlab.com/papertext/paperback:$CI_COMMIT_SHA .
    - buildah push registry.gitlab.com/papertext/paperback:latest
    - buildah push registry.gitlab.com/papertext/paperback:$CI_COMMIT_SHA

deploy prod:
  stage: deploy
  only:
    refs:
      - prod
  trigger:
    project: papertext/papertext_dev
    branch: prod

deploy dev:
  stage: deploy
  only:
    refs:
      - dev
  trigger:
    project: papertext/papertext_dev
    branch: dev
