version: 2

sphinx:
  configuration: src/paperback_docs/conf.py

formats: all

python:
  version: 3.8
  install:
      - method: pip
        path: .
      - requirements: src/paperback_docs/requirments.txt
