version: 2

sphinx:
  configuration: src/documentation/conf.py

formats: all

python:
  version: 3.8
  install:
      - method: pip
        path: .
      - requirements: src/documentation/requirments.txt
