version: 2

sphinx:
  configuration: src/paperback_docs/conf.py

formats: all

python:
  version: 3.8
  install:
      - method: pip
        path: .
      - method: pip
        path: typing_extensions
#    - requirements: paperback_docs/requirements.txt
